# Generated by Django 3.1.7 on 2021-03-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210314_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='trello_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='trello_id',
            field=models.CharField(blank=True, max_length=291),
        ),
    ]
