FROM node:14-alpine

RUN mkdir -p /app
WORKDIR /app

ENV PATH=/app/node_modules/.bin:$PATH

COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

RUN npm install --silent
RUN npm install react-scripts -g --silent

CMD ["npm", "start"]
