version: '3'

services:
  
  admin:
    container_name: admin
    build:
      context: ./backend
      dockerfile: Dockerfile-prod
    expose:
     - '5000'
    environment:
      - APP_SETTINGS=admin.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@admin-db:5432/admin_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@admin-db:5432/admin_test
    depends_on:
      - admin-db
    links:
      - admin-db
  
  admin-db:
    container_name: admin-db
    build:
      context: ./services/admin/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=development
        - ADMIN_SERVICE_URL=${ADMIN_SERVICE_URL}
    ports:
      - '3007:80'
    depends_on:
      - admin
    links:
      - admin

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - admin
    links:
      - admin
      - frontend
