version: '3'

services:

  admin:
    container_name: admin
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    volumes:
      - './backend:/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=admin.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@admin-db:5432/admin_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@admin-db:5432/admin_test
    depends_on:
      - admin-db
    links:
      - admin-db

  admin-db:
    container_name: admin-db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile-dev
    volumes:
      - './frontend:/app'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - ADMIN_SERVICE_URL=${ADMIN_SERVICE_URL}
    depends_on:
      - admin
    links:
      - admin

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
    - 80:80
    depends_on:
    - admin
    - frontend
