export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const REVOKED_EMPLOYEE = 'REVOKED_EMPLOYEE';
export const SHOW_ADD_EMPLOYEE = 'SHOW_ADD_EMPLOYEE';
export const CHANGE_ACCESS = 'CHANGE_ACCESS';
export const SHOW_ALL_EMPLOYEE = 'SHOW_ALL_EMPLOYEE';
export const SHOW_CURRENT_EMPLOYEE = 'SHOW_CURRENT_EMPLOYEE';
export const SHOW_REVOKED_EMPLOYEE = 'SHOW_REVOKED_EMPLOYEE';
