[build]
  publish = "dist"
  command = "cd on-boarding-off-boarding-app && npm run build"
  functions = "dist/functions" 
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200