# example netlify.toml
[build]
  command = "npm run build"
  functions = "function-build"
  publish = "build"

[redirects]
  to = "/.netlify/functions/:splat"
  from = "/api/*"
  status = 200
  force = true