FROM python:3.8

RUN apt-get update -yqq \
    && apt-get install -yqq --no-install-recommends \
    netcat \
    && apt-get -q clean


RUN mkdir -p /app
WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

RUN pip install -r requirements.txt

COPY . /app

CMD ["./entrypoint.sh"]

