# Generated by Django 3.1.3 on 2021-03-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210313_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
