version: '3'

services:
  admin:
    container_name: admin
    build:
      context: ./services/admin
      dockerfile: Dockerfile-dev
    volumes:
      - './services/admin:/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig
